<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <!-- <TargetFramework>net10.0</TargetFramework> -->
    <AssemblyName>MeowSci.PartsNow</AssemblyName>
    <!-- <LangVersion>13</LangVersion> -->
    <!-- <Nullable>enable</Nullable> -->
    <!-- <ImplicitUsings>disable</ImplicitUsings> -->
    <!-- <GenerateDocumentationFile>false</GenerateDocumentationFile> -->
    <!-- <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StarMap.API" Version="0.3.6" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\parts-now.lib\parts-now.lib.csproj" />
    <ProjectReference Include="..\ksa-abstractions.lib\ksa-abstractions.lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Brutal.Core.Common" Condition="Exists('$(KSAFolder)Brutal.Core.Common.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Numerics" Condition="Exists('$(KSAFolder)Brutal.Core.Numerics.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Numerics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui" Condition="Exists('$(KSAFolder)Brutal.ImGui.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.ImGui.Abstractions" Condition="Exists('$(KSAFolder)Brutal.ImGui.Abstractions.dll')">
      <HintPath>$(KSAFolder)Brutal.ImGui.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Brutal.Core.Strings" Condition="Exists('$(KSAFolder)Brutal.Core.Strings.dll')">
      <HintPath>$(KSAFolder)Brutal.Core.Strings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="KSA" Condition="Exists('$(KSAFolder)KSA.dll')">
      <HintPath>$(KSAFolder)KSA.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="mod.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
