<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RequiresKSAAssemblies>false</RequiresKSAAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <Reference Include="Brutal.Core.Numerics"><HintPath>$(KSAFolder)Brutal.Core.Numerics.dll</HintPath></Reference>
    <Reference Include="Brutal.Core.Common"><HintPath>$(KSAFolder)Brutal.Core.Common.dll</HintPath></Reference>
    <Compile Include="../iron-man.lib/IronManFlightPatches.cs" Link="IronManFlightPatches.cs" />
    <Compile Include="../iron-man.lib/IronManRenderPatches.cs" Link="IronManRenderPatches.cs" />
    <Compile Include="../iron-man.lib/IronManFlightComputerPatches.cs" Link="IronManFlightComputerPatches.cs" />
    <Compile Include="../iron-man.lib/IronManFlightSettings.cs" Link="IronManFlightSettings.cs" />
  </ItemGroup>
</Project>
