<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <Compile Include="../dent-wizard.lib/LaunchMath.cs" Link="LaunchMath.cs" />
    <Compile Include="../dent-wizard.lib/LaunchRequest.cs" Link="LaunchRequest.cs" />
    <Compile Include="../dent-wizard.lib/DentWizardSubmod.cs" Link="DentWizardSubmod.cs" />
    <Reference Include="Brutal.Core.Numerics"><HintPath>$(KSAFolder)Brutal.Core.Numerics.dll</HintPath></Reference>
    <Reference Include="BepuUtilities"><HintPath>$(KSAFolder)BepuUtilities.dll</HintPath></Reference>
  </ItemGroup>
</Project>
