<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RequiresKSAAssemblies>false</RequiresKSAAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <Compile Include="../ksa-abstractions.lib/PhysicsFrameHook.cs" Link="PhysicsFrameHook.cs" />
    <Compile Include="../garrys-torch.lib/GarrysTorchPatches.cs" Link="GarrysTorchPatches.cs" />
  </ItemGroup>
</Project>
